require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmd"

-- spec "user.aerial"
spec "user.alpha"
spec "user.autopairs"
spec "user.autotag"
spec "user.bufdelete"
spec "user.bufferline"
spec "user.cmp"
spec "user.comment"
spec "user.devicons"
spec "user.diffview"
spec "user.gitsigns"
spec "user.illuminate"
spec "user.indentline"
spec "user.lspconfig"
spec "user.lualine"
spec "user.mason"
spec "user.navic"
spec "user.neodev"
spec "user.null-ls"
spec "user.nvimtree"
spec "user.oscyank"
spec "user.outline"
spec "user.telescope"
spec "user.tmux"
spec "user.toggleterm"
spec "user.treesitter"
spec "user.whichkey"

spec "user.colorschemes.tokyonight"
spec "user.colorschemes.kanagawa"
spec "user.colorschemes.cyberdream"

-- Chainsaw does not support C yet
-- spec "user.extras.chainsaw"
-- spec "user.extras.cmp-tabnine"
spec "user.extras.colorizer"
-- spec "user.extras.context"
spec "user.extras.harpoon"
spec "user.extras.hex"
spec "user.extras.mind"
spec "user.extras.modicator"
-- spec "user.extras.moveline"
-- spec "user.extras.navbuddy"
spec "user.extras.neogen"
spec "user.extras.neoscroll"
-- spec "user.extras.noice"
spec "user.extras.nui"
-- spec "user.extras.neotab"
spec "user.extras.persistence"
spec "user.extras.pretty-fold"
spec "user.extras.rainbow"
spec "user.extras.rustacean"
-- spec "user.extras.strict"
spec "user.extras.todo-comments"
spec "user.extras.trouble"

spec "user.languages"

require "user.lazy"
require "user.colorscheme"
